modLoader="javafml"
loaderVersion="[36,)"
license="Apache License Version 2.0"

[[mods]]
modId="mcreator_link"
version="1.3"
displayName="MCreator Link"
description="API for Minecraft Forge mods to connect to the hardware devices such as Arduino or Raspberry Pi."
credits="Pylo and MCreator development team."
displayURL="https://mcreator.net/link"
authors="Pylo"
logoFile="logo.png"

[[dependencies.test]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
